spring:
  application:
    name: Spring_demo
  datasource:
    url: jdbc:postgresql://localhost:5432/myDb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  servlet:
    context-path: /myDb
